- name: Configure Cisco Banner
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_ssh_pass: cisco
    ansible_network_os: ios
    ansible_connection: network_cli

  tasks:
    - name: Set banner message
      cisco.ios.ios_config:
        lines:
          - banner motd ^C
          - "  *** Unauthorized access prohibited ***"
          - "  *** This system is monitored ***"
          - ^C
