- name: Configure ACLs on Cisco
  hosts: all
  gather_facts: no
  vars_files:
    - acl_config.txt

  tasks:
    - name: Apply ACL configuration
      cisco.ios.ios_config:
        src: acl_template.j2

